// Owned metadata must never authorize deleting user paths after comment edits.
import { afterEach, expect, test } from "bun:test";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { cleanup, hasZig, newInstall, run, WIN } from "./harness.ts";
afterEach(cleanup);
for (const shell of ["bash", "zsh", "fish"] as const) {
 test.skipIf(!hasZig || WIN)(`SC-IDEMPOTENT review: ${shell} ownership edits retain profile and user directories`, () => {
  const i = newInstall(); const env = { ZDOTDIR: i.home, XDG_CONFIG_HOME: join(i.home, "config") };
  const file = shell === "fish" ? join(i.home, "config/fish/completions/dsh.fish") : join(i.home, shell === "bash" ? ".bashrc" : ".zshrc");
  if (shell !== "fish") writeFileSync(file, "");
  expect(run(i, ["manager", "completion", "install", shell], { env }).status).toBe(0);
  const owned = readFileSync(file, "utf8");
  const token = shell === "fish" ? "created" : "existing";
  for (const edit of [owned.replace(`${shell} ${token}`, `${shell} ${token === "created" ? "existing" : "created"}`), owned.replace(`${shell} ${token}`, `${shell} created:2`), owned.replace("Generated by", "Generated bx")]) {
   writeFileSync(file, edit);
   for (const action of ["install", "uninstall"]) { expect(run(i, ["manager", "completion", action, shell], { env }).status).toBe(1); expect(readFileSync(file, "utf8")).toBe(edit); }
   expect(existsSync(join(file, ".."))).toBe(true);
  }
 }, 300_000);
}
