# Generated by dsh-manager; respects an already initialized compinit.
if (( ! $+functions[compdef] )); then
    autoload -Uz compinit
    compinit -D -i
fi
_dsh_manager_complete() {
    local -a candidates
    local candidate
    while IFS= read -r candidate; do
        candidates+=("$candidate")
    done < <(@DSH@ manager __complete --shell zsh -- "${words[@]:1:$((CURRENT - 1))}" 2>/dev/null)
    (( ${#candidates} )) && compadd -- "${candidates[@]}"
}
if [[ -n ${_comps[dsh]-} && ${_comps[dsh]} != _dsh_manager_complete ]]; then
    print -ru2 -- 'dsh completion collision: existing Zsh completion kept'
else
    compdef _dsh_manager_complete dsh
fi
