# Generated by dsh-manager; command words and candidates remain data.
set -l existing (complete -c dsh)
if set -q _dsh_manager_completion_owner; and test "$_dsh_manager_completion_owner" = @DSH@; and test "$_dsh_manager_completion_registration" = (string join \n -- $existing)
    # Already loaded in this session.
else if test (count $existing) -gt 0; or functions -q _dsh_manager_complete
    printf '%s\n' 'dsh completion collision: existing Fish completion kept' >&2
else
    function _dsh_manager_complete
        set -l prior (commandline -opc)
        set -l prefix (commandline -ct)
        command @DSH@ manager __complete --shell fish -- $prior[2..-1] "$prefix" 2>/dev/null
    end
    complete -c dsh -f -a '(_dsh_manager_complete)'
    set -g _dsh_manager_completion_owner @DSH@
    set -g _dsh_manager_completion_registration (string join \n -- (complete -c dsh))
end
