# Generated by dsh-manager; candidates are data, never eval input.
if { [[ ${_dsh_manager_completion_owner-} != @DSH@ ]] && { complete -p dsh >/dev/null 2>&1 || declare -F _dsh_manager_complete >/dev/null; }; } ||
   { complete -p dsh >/dev/null 2>&1 && [[ $(complete -p dsh) != *' -F _dsh_manager_complete dsh' ]]; }; then
    printf '%s\n' 'dsh completion collision: existing Bash completion kept' >&2
else
    _dsh_manager_complete() {
        local candidate
        COMPREPLY=()
        while IFS= read -r candidate; do
            printf -v candidate '%q' "$candidate"
            COMPREPLY+=("$candidate")
        done < <(command @DSH@ manager __complete --shell bash -- "${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)
    }
    _dsh_manager_completion_owner=@DSH@
    complete -F _dsh_manager_complete dsh
fi
