# Generated by dsh-manager; candidates are data, never eval input.
_dsh_manager_complete() {
    local candidate
    COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(@DSH@ manager __complete --shell bash -- "${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)
}
if complete -p dsh >/dev/null 2>&1 && [[ $(complete -p dsh) != *' -F _dsh_manager_complete dsh' ]]; then
    printf '%s\n' 'dsh completion collision: existing Bash completion kept' >&2
else
    complete -F _dsh_manager_complete dsh
fi
