# Generated by dsh-manager; only constant AST words reach the native offline query.
# PowerShell has no public completer lookup/unregister API; registration-file collisions
# are checked by the manager. A completer loaded by another module may register later.
Register-ArgumentCompleter -Native -CommandName dsh,dsh.exe -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $words = [System.Collections.Generic.List[string]]::new()
    $elements = $commandAst.CommandElements
    for ($i = 1; $i -lt $elements.Count; $i++) {
        $element = $elements[$i]
        if ($element.Extent.StartOffset -ge $cursorPosition) { break }
        if ($element.Extent.EndOffset -ge $cursorPosition -and $wordToComplete.Length -gt 0) { break }
        if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            $words.Add($element.Value)
        } elseif ($element -is [System.Management.Automation.Language.CommandParameterAst] -and $null -eq $element.Argument) {
            $words.Add($element.Extent.Text)
        } else {
            return # Never evaluate variables, expressions or command substitutions.
        }
    }
    $words.Add($wordToComplete)
    $separator = [char]0x1f
    foreach ($word in $words) {
        if ($word.IndexOf([char]0) -ge 0 -or $word.IndexOf($separator) -ge 0) { return }
    }
    $manager = Get-Command -Name @DSH@ -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $manager) { return }
    $oldWords = [Environment]::GetEnvironmentVariable('DSH_COMPLETE_WORDS', 'Process')
    $oldEncoding = [Console]::OutputEncoding
    try {
        [Environment]::SetEnvironmentVariable('DSH_COMPLETE_WORDS', [string]::Join($separator.ToString(), $words.ToArray()), 'Process')
        [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
        foreach ($candidate in (& $manager.Source manager __complete --shell pwsh --words-env 2>$null)) {
            $insert = if ($candidate -cmatch '^[A-Za-z0-9_.+@:-]+$') { $candidate } else { "'" + $candidate.Replace("'", "''") + "'" }
            [System.Management.Automation.CompletionResult]::new($insert, $candidate, 'ParameterValue', $candidate)
        }
    } finally {
        [Environment]::SetEnvironmentVariable('DSH_COMPLETE_WORDS', $oldWords, 'Process')
        [Console]::OutputEncoding = $oldEncoding
    }
}
